spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/star?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    filters: wall,mergeStat

#多数据源情况的配置
star:
  muti-datasource:
    open: false
    url: jdbc:mysql://127.0.0.1:3306/star_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    dataSourceNames:
    - dataSourceStar
    - dataSourceBiz